### ISSUE TITLE
Tarifs animation fabmob

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/rtfm#18]
# tarif à la 1/2 journée
1. Animateur responsable. 
160€ tvac
2. Animateur accompagnant
100€ tvac

## pour facturation par smart. 
- soit via son activité, avec tva 21%
- soit via formateur associé, avec tva 0%

```
Formation professionnelle et enseignement de matières scolaires
**Justification:**
Formation d’élèves aux technologies numériques dans les écoles. 3,5
journées
Exemption de la TVA - Article 44 §2, 4° du Code.
```

**Comment by DewiBrunet** [comment]
J'ai à nouveau du mal à savoir où mettre les choses dans github... et je comprends donc pourquoi personne veux l'utiliser^^ 
J'ai créé un md "FAQ tarification", tout y est j'espère :
 https://github.com/openfab-lab/FabMob/blob/master/FAQ/FAQ_facturation.md

on close l'issue du coup?

**Comment by nicolasdb** [comment]
Elle est bien ta page. ;) nice. 

Et oui, je suis d'accord aussi que c'est l'enfer de s'y retrouver. 
C'est pour ça qu'il faut que quoi qu'on fasse, le point d'entrée, de référence quand on se pose une question, ça doit devenir le RTFM. 
Une question, un reflexe, on cherche dans le RTFM. 

![image](https://user-images.githubusercontent.com/12049360/53801379-4be06f00-3f3f-11e9-9691-68da6bbc617d.png)


- Où est-ce qu'on range le PQ? >RTFM
- C'est quoi les status de l'asso? >RTFM
- Comment j'encode ma note de frais? >RTFM
- Elle coute combien la maes au frigo? >RTFM!
- c'est quoi ce RTFM? > RTFM!!!

De là, soit on y trouve l'information qu'on cherche, soit le lien vers l'information, soit on crée une issue pour demander l'information qui devra faire le sujet d'une entrée dans le RTFM.

1. C'est quoi les tarif fabmob? >RTFM puis lien vers >FABMOB/tarifs.md _par exemple_

Si l'info relative à fabmob fait sens d'être centralisée dans le repo adhoc, il faut 
- soit dupliquer l'info dans le RTFM
_mais je n'aime pas que ce soit dupliqué, on risque de modifier dans fabmob sans mettre à jour dans RTFM et c'est à nouveau le bordel_
- soit faire référence vers le doc sur le repo Fabmob = document unique à jour. 

2. Pourquoi y a plus de ClubMaté au frigo? Est-ce qu'il est possible d'utiliser le vélo cargo en dehors du FABMOB? 

- [ ] >RTFM. Ha, rien encore à ce sujet? 
- [ ] >Issue. contexte, objectif, proposition. 
- [ ] la réponse doit faire l'objet d'une nouvelle entrée dans le RTFM, donc branche>MD file>Pull request>Peer Review>merge&delete branch.

**Comment by nicolasdb** [comment]
La structure du RTFM est aussi une question. 
Je pense aujourd'hui que si déjà on met en vrac sur le repo, c'est déjà bien. 
Petit à petit, on pourra rassembler les documents par des catégories et organiser au fur et à mesure qu'on le complète.

**Comment by nicolasdb** [comment]
J'ai réunis ça là:
https://openfab.gitbook.io/rtfm/faq/prestation-animateur

on peut se dire que ce tarif se rediscutera pour les projets suivant. 
Je clos cette issue.
