### ISSUE TITLE
accounting of lasersaur time

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/rtfm#4]
MD files : https://github.com/openfab-lab/rtfm/blob/master/Tools/Tools_lasersaur_Book.md

@nicolasdb commented on [Sat Jan 05 2019](https://github.com/openfab-lab/devis-et-facturation/pull/47)

I'm starting the manual for accouting. 
Trying to already match also the naming from zoho.

List of rewards
- `x` crrr
- `x` XP
- `x` loot

---

@nicolasdb commented on [Sat Jan 05 2019](https://github.com/openfab-lab/devis-et-facturation/pull/47#issuecomment-451660403)

![image](https://user-images.githubusercontent.com/12049360/50725524-03533380-10ff-11e9-8e31-b5a08746c983.png)
![image](https://user-images.githubusercontent.com/12049360/50725537-31387800-10ff-11e9-9b12-98cf79f14569.png)

---

@nicolasdb commented on [Sat Jan 05 2019](https://github.com/openfab-lab/devis-et-facturation/pull/47#issuecomment-451661978)

![image](https://user-images.githubusercontent.com/12049360/50725565-9724ff80-10ff-11e9-9899-7c1d111dc55b.png)

---

@nicolasdb commented on [Sat Jan 05 2019](https://github.com/openfab-lab/devis-et-facturation/pull/47#issuecomment-451678131)

@satblip 
Est-ce que cette info est pertinente? Ne va t'elle pas être gérée autrement avec Zoho? Et le wallet online?

**Comment by satblip** [comment]
@nicolasdb J'ai un peu du mal à suivre de quoi tu parles ?

**Comment by nicolasdb** [comment]
Est-ce que ça sert à quelque chose de documenter ce process si on va gérer cette facturation via le wallet en ligne?

**Comment by satblip** [comment]
ok je comprends. Pour moi, oui et non, le process dans zoho, non. Par contre ce sera bien que cela soit dans le RTFM pour le principe du wallet (too soon now) et que cela soit clair. Donc pour le moment, je dirais hold on ;)

**Comment by nicolasdb** [comment]
yes, je revois un peu le flow pour les ajouts dans le RTFM. 
En même tps, j'essaye de maitriser et documenter l'import des données des comptes dans zoho. #3 
Et j'ai retrouvé cet doc sur le laser dans devis/facturation. Je range en même tps.

**Comment by nicolasdb** [comment]
link to PR #5

**Comment by nicolasdb** [comment]
en ligne sur https://github.com/openfab-lab/rtfm/blob/master/Tools/Tools_lasersaur_Book.md
